### ISSUE TITLE
Non-long/negatives via JS?

### ISSUE THREAD

**Issue by bkardell** [smockle/headingoffset-polyfill#13]
given...
```html
<div id="a" headingoffset="-2">
   <h1>A</h1>
</div>

<div id="b" headingoffset="fish">
   <h1>B</h1>
</div>
```

While the invalid values (https://html.spec.whatwg.org/#limited-to-only-non-negative-numbers) don't actively seem to screw up the `aria-level` that is applied (or isn't), the property seems to give other values:

```
> console.log(a.headingOffset) 
-2

> console.log(b.headingOffset)
NaN
```

Is that right? It's not how some similar things like `colSpan` work...  Perhaps what should happen here is that there should be a conceptual default value of 0 (that's what `colSpan` does) which should be returned by that API if it can't parse.  I imagine this is what you are doing in practice for computing anyway, shouldn't it log the same?

**Comment by keithamus** [comment]
>  Perhaps what should happen here is that there should be a conceptual default value of 0 (that's what colSpan does) which should be returned by that API if it can't parse.

Yeah that's correct. This is a bug in this implementation.

**Comment by smockle** [comment]
Thanks for reporting this! Opened https://github.com/smockle/headingoffset-polyfill/pull/14 with a fix.
